/* CTRC — MỤC TIÊU TUẦN (seed từ giáo án Level 3: 301–310, 305+/310+).
   Chỉnh sửa realtime trong app (Manager → 🎯 Mục tiêu tuần) — bản sửa lưu localStorage, KHÔNG đụng file này.
   Đổi seed gốc thì sửa file này. */
window.CTRC_OBJECTIVES = {
 "301": {
  "1": "Mục tiêu kiến thức: Trong bài học tuần 1 các con sẽ được lắng nghe câu chuyện “ Anky hay bắt chước” và các kỹ năng tư duy. Thông qua câu chuyện học sinh được học về khái niệm Kiểu mẫu, dựa vào quy luật sắp xếp của các hình ảnh, học sinh xác định trình tự của chuỗi lặp và sáng tạo Kiểu mẫu bằng các bộ phận trên cơ thể mình. Biết liên hệ quy luật kiểu mẫu với các hình ảnh thực tế trong cuộc sống. Dựa vào tính chất quy luật, các con sẽ biết cách sắp xếp logic các thông tin, dữ liệu và cách giải quyết vấn đề tốt hơn. Thông qua bài tập, các con được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, xác định quy luật sắp xếp. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "2": "Mục tiêu kiến thức: Trong bài học tuần 2 các con được tham gia trò chơi hoạt động “ KIỂU MẪU VUI VẺ” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi hoạt động học sinh biết cách quan sát các chuỗi hình ảnh được sắp xếp theo một quy luật lặp đi lặp lại, xác định trình tự của chuỗi lặp và tìm hình ảnh phù hợp điền vào vị trí còn thiếu.  Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, suy luận các tình tiết, diễn biến của các câu hỏi. Rèn luyện khả năng lắng nghe, chơi theo quy luật và phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "3": "Mục tiêu kiến thức: Trong bài học tuần 3 các con được tham gia trò chơi hoạt động “KIỂU MẪU VUI VẺ” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi cơ bản học sinh biết cách quan sát, xác định quy luật sắp xếp của các hình ảnh và dự đoán hình tiếp theo để tạo thành 1 chuỗi kiểu mẫu với các thẻ nhạc cụ và sáng tạo đoạn kiểu mẫu âm thành bằng các bộ phận trên cơ thể. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và ghi nhớ. Rèn luyện khả năng suy luận phân tích để phát triển tư duy logic. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "4": "Mục tiêu kiến thức: Trong bài học tuần 4 các con được tham gia trò chơi hoạt động “KIỂU MẪU VUI VẺ” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi nâng cao học sinh biết cách quan sát, xác định quy luật sắp xếp của các hình ảnh và dự đoán hình tiếp theo để tạo thành 1 chuỗi kiểu mẫu với các thẻ số. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và sự phản ứng linh hoạt, nhạy bén trong quá trình tìm quy luật. Rèn luyện khả năng sáng tạo bằng việc tưởng tượng, phát họa hình ảnh bằng mắt và thể hiện bằng câu chuyện sắng tạo. Cải thiện ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình."
 },
 "302": {
  "1": "Nội dung bài học: Câu chuyện: \"NHỮNG CUỘC PHIÊU LƯU MÙA THU\" \nMục tiêu kiến thức: Trong bài học tuần 1 các con sẽ được lắng nghe câu chuyện “ Những cuộc phiêu lưu mùa thu” và 6 trang của sách hoạt động (Trang 1-6). Thông qua câu chuyện học sinh  được làm quen với phương pháp so sánh trực tiếp để đo lường. Học sinh học các phép đo khác nhau như học ghép hai đầu que lại với nhau để đo, duỗi thẳng dây leo để đo độ dài của chúng, và đếm từng tảng đá một để so sánh số lượng. Đặc biệt để đo chiều dài của đồ vật cần xuất phát cùng 1 điểm. Với 6 trang của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, con biết cách đo lường đồ vật và so sánh nhiều hơn, ít hơn. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "2": "Mục tiêu kiến thức: Trong bài học tuần 2 các con được tham gia trò chơi hoạt động “ SO SÁNH và ĐO LƯỜNG” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi hoạt động học sinh biết cách phân biệt dài ngắn thông qua so sánh trực tiếp. Học sinh cần vượt qua các thử thách bằng cách trả lời câu hỏi do giáo viên đưa ra để xác định được khái niệm so sánh dài hơn, ngắn hơn, cao nhất, thấp nhất, nhiều hơn, ít hơn,to nhất, nhỏ nhất.  Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và so sánh độ dài, ngắn. Rèn luyện khả năng suy luận và định hướng trong không gian. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "3": "Mục tiêu kiến thức: Trong bài học tuần 3 các con được tham gia trò chơi hoạt động “XE TẢI CHỞ HOA” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi hoạt động học sinh biết cách phân biệt dài ngắn thông qua so sánh trực tiếp. Học sinh cần vượt qua các thử thách bằng cách trả lời câu hỏi do giáo viên đưa ra để mang về cho mình những miếng ghép xe tải sau đó ghép lại và so sánh độ dài của mỗi xe. Xác định để đo được chính xác chiều dài cần xuất phát tại cùng một điểm.  Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và so sánh độ dài, ngắn. Rèn luyện khả năng suy luận phân tích để phát triển tư duy logic. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "4": "Mục tiêu kiến thức: Trong bài học tuần 4 các con được tham gia trò chơi “XE TẢI CHỞ HOA” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi hoạt động học sinh biết cách phân biệt dài ngắn thông qua so sánh trực tiếp. Học sinh cần vượt qua các thử thách bằng cách giải quyết các bài toán tư duy để mang về cho mình những miếng ghép xe tải sau đó ghép lại và so sánh độ dài của mỗi xe. Xác định để đo được chính xác chiều dài cần xuất phát tại cùng một điểm. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và so sánh độ dài, ngắn. Phát triển khả năng sáng tạo, trí tưởng tượng phong phú của bản thân. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình."
 },
 "303": {
  "1": "Nội dung bài học: Câu chuyện: \"REX VÀ CHIẾC XE ĐẨY THẦN KỲ\" \nMục tiêu kiến thức: Trong bài học tuần 1 các con sẽ được lắng nghe câu chuyện “Rex và chiếc xe đẩy thần kỳ” và các kỹ năng tư duy. Thông qua câu chuyện học sinh học cách cộng liên tiếp các con số lớn tăng dần. Trải nghiệm phép cộng và phép trừ của những con số và các hoạt động bằng cách cộng 5 củ khoai tây của Dipo với 4 củ khoai tây của Tera để ra số 9 và các khái niệm khác của câu chuyện. Thông qua bài tập, các con được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình. Thông qua câu chuyện con được rèn luyện về kỹ năng biết nhường nhịn, chia sẻ cùng nhau. Đồng thời nhắc nhở con tránh những việc làm, hành động xấu, nếu không sẽ gặp hậu quả đáng tiếc. con biết cách đếm theo nhóm, so sánh nhiều hơn, ít hơn. Phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "2": "Mục tiêu kiến thức: Trong bài học tuần 2 các con được tham gia trò chơi hoạt động “ DINOSAURS” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi hoạt động học sinh được rèn luyện khả năng quan sát, vừa kết hợp ca hát và luyện tài nhanh mắt để tìm ra các thẻ khủng long có số lượng tương ứng. Ngoài ra học sinh quan sát các thẻ khủng long và tìm điểm chung của 2 thẻ hình, giải thích về câu trả lời của mình. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và so sánh độ dài, ngắn, cao thấp. Rèn luyện khả năng suy luận và tìm điểm khác biệt. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "3": "Mục tiêu kiến thức: Trong bài học tuần 3 các con được tham gia trò chơi cơ bản “ DINOSAURS” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi các con nhận biết mối tương quan giữa các con số, quy luật sắp xếp của các con số và khả năng phản xạ, thực hiện phép tính trong phạm vi 5. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và ghi nhớ. Rèn luyện quá trình làm việc nhóm, khả năng suy luận phân tích để phát triển tư duy logic, khả năng suy luận và tìm điểm khác biệt. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "4": "Mục tiêu kiến thức: Trong bài học tuần 4 các con sẽ được tham gia trò chơi nâng cao “DINOSAURS” và các kỹ năng tư duy. Thông qua trò chơi cơ bản học sinh được rèn luyện khả năng quan sát, tính toán, thực hiện phép cộng các số có 1 chữ số. Trò chơi hoạt động sẽ mang tới sự gần gũi, thân quen giúp các con dễ dàng tiếp thu nội dung kiến thức và tăng sự thích thú trong học tập, sự phối hợp làm việc nhóm, khả năng lắng nghe, suy luận.. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, tách và gộp số trong phạm vi 5. Thông qua các hoạt động trò chơi giúp các con có sự phản xạ nhanh trong việc tính toán. Rèn luyện khả năng lắng nghe, chơi theo quy luật và phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình."
 },
 "304": {
  "1": "Mục tiêu câu chuyện: Học sinh học quá trình đổi chác khi Rex mua cây thông Noel và đồ trang trí chỉ có cà rốt. Các con học được khái niệm rằng: nếu A=B và B=C thì A=C.",
  "2": "Mục tiêu bài học: Trong bài học tuần trước, thông qua câu truyện học sinh học quá trình đổi chác khi Rex mua cây thông Noel và đồ trang trí chỉ có cà rốt. Các con học được khái niệm rằng: nếu A=B và B=C thì A=C. Thì trong trò chơi tuần này, các con được rèn luyện về thể chất và sự nhanh nhẹn của bản thân kèm theo đó rèn luyện cách quy đổi theo bảng giá cho trước. Đội nào đổi được ngôi sao để treo lên cây thông trước sẽ giành chiến thắng.",
  "3": "Mục tiêu bài học : Trong bài học tuần 3 các con sẽ được tham gia trò chơi cơ bản  “Ngôi sao vàng” và 6 trang tiếp theo của sách hoạt động từ trang số 13 – trang 18. Thông qua trò chơi các con hiểu được khái niệm nếu A=B và B=C thì A=C. Các con sẽ học được cách so sánh các đồ vật qua vật trung gian. Trò chơi này sẽ mang tới sự gần gũi, thân quen giúp các con dễ dàng tiếp thu nội dung kiến thức và tăng sự thích thú trong học tập. Với 6 trang tiếp theo của sách hoạt động tập trung chủ yếu phát triển tư duy cơ bản sự chú ý và tập trung, tư duy toán học và tư duy logic tổng hợp. Điều đó được thể hiện rõ qua các trang bài tập\nMục tiêu kỹ năng: Trong bài học này các con sẽ tăng cường được khả năng quan sát thật kỹ lưỡng và tìm ra hình có đặc điểm phù hợp với tiêu chí.",
  "4": "Mục tiêu bài học : Trong bài học tuần 4 các con sẽ được tham gia trò chơi nâng cao:  “Ngôi sao vàng” và 6 trang tiếp theo của sách hoạt động từ trang số 19 – trang 24. Thông qua trò chơi các con sẽ tiếp tục được rèn luyện để nhận thức được mối liên hệ nếu A=B, B=C  thì A=C. Các con hiểu được cách quy đổi các đồ vật và sử dụng luật đổi linh hoạt để chiến thắng trong trò chơi. Trò chơi này sẽ mang tới sự gần gũi, thân quen giúp các con dễ dàng tiếp thu nội dung kiến thức và tăng sự thích thú trong học tập. Với 6 trang tiếp theo của sách hoạt động tập trung chủ yếu phát triển tư duy toán học hình học, tư duy toán học con số và hoạt động và tư duy sáng tạo. Điều đó được thể hiện rõ qua các trang bài tập\nMục tiêu kỹ năng: Trong bài học này các con sẽ tăng cường được khả năng quan sát , so sánh hình ảnh xác định được vị trí tương tự, tăng khả năng tập trung, ghi nhớ để sử dụng luật đổi phù hợp, chính xác."
 },
 "305": {
  "1": "Mục tiêu kiến thức:Thông qua Câu chuyện “Anh có phải là anh em trai” các con học cách tìm ra các điểm tương đồng và khác biệt giữa các đối tượng. Các con thực hành quan sát tìm ra điểm giống và khác nhau giữa các bạn trong lớp. Và 6 trang tiếp theo của sách hoạt động các con được rèn luyện các kỹ năng như sau. \nMục tiêu kỹ năng: Rèn luyện khả năng cân bằng hai bán cầu não thông qua làm bài tập vẽ bằng 2 tay cùng lúc, phân biệt giống và khác nhau.",
  "2": "Mục tiêu kiến thức:\nTuần này con tham gia trò chơi “Gia đình của chúng ta”, thông qua hoạt động trò chơi các con biết các so sánh các đồ vật với nhau. Bên cạnh đó, trò chơi còn tăng cường khả năng quan sát cho các con, giúp con phát triển tư duy logic thông qua tìm điểm giống nhau và khác nhau. Ngoài ra, với 6 trang sách hoạt động các con còn được rèn luyện các dạng tư duy như sau. \nMục tiêu kỹ năng: Rèn luyện kỹ năng tư duy cơ bản, tư duy logic, phân biệt điểm giống và khác nhau, sắp xếp các đồ vật theo nhóm tương ứng",
  "3": "Mục tiêu kiến thức: Trong bài học tuần 3 các con sẽ được tham gia trò chơi cơ bản “Gia đình của chúng ta” giúp con phát triển tư duy Logic thông qua hoạt động tìm những điểm tương đồng và khác biệt giữa các hình. Và 6 trang tiếp theo của sách hoạt động (Trang 13-28). \nMục tiêu kỹ năng: Bài học tuần này với các trò chơi trong 6 trang sách hoạt động, đặc biệt là trò chơi nâng cao, giúp các con có kỹ năng đối diện và giải quyết vấn đề, kỹ năng tham gia một trò chơi nhóm có luật.",
  "4": "Mục tiêu kiến thức: Trong bài học tuần 4 các con sẽ được tham gia trò chơi nâng cao “Gia đình của chúng ta” giúp học sinh phát triển tư duy Logic thông qua hoạt động tìm những điểm tương đồng và khác biệt giữa các hình. Và 6 trang tiếp theo của sách hoạt động (Trang 19-24). \nMục tiêu kỹ năng: Bài học tuần này với các trò chơi trong 6 trang sách hoạt động, đặc biệt là trò chơi nâng cao, giúp các con có kỹ năng đối diện và giải quyết vấn đề, kỹ năng tham gia một trò chơi nhóm có luật"
 },
 "305+": {
  "1": "Mục tiêu bài học : Trong bài học tuần 1 các con sẽ được tham gia trò chơi “Âm nhạc vui vẻ” và 6 trang đầu tiên của sách hoạt động từ trang 1 đến trang 6. Thông qua bộ trò chơi học sinh biết cách tạo tổng 10 từ thẻ trò chơi. Với 6 trang đầu tiên của sách hoạt động tập trung chủ yếu phát triển:\nMục tiêu kỹ năng: Trong bài học này các con sẽ tăng cường được khả năng quan sát và tính toán của mình thông qua các bài tập và trò chơi. Ngoài ra, các con còn biết chia sẻ và thể hiện những ý tưởng sáng tạo của mình với tập thể.",
  "2": "Mục tiêu bài học : Trong bài học tuần 2 các con sẽ được tham gia trò chơi “ Xe tải hoa” và 6 trang tiếp theo của sách hoạt động từ trang 7 đến trang 12. Thông qua trò chơi các con hiểu So sánh độ dài của những chiếc xe tải, phân biệt dài hơn và ngắn hơn. Rèn luyện kỹ năng vận động tinh, thuyết trình về sản phẩm của mình. Trò chơi này sẽ mang tới sự gần gũi, thân quen giúp các con dễ dàng tiếp thu nội dung kiến thức và tăng sự thích thú trong học tập. Với 6 trang tiếp theo của sách hoạt động tập trung chủ yếu phát triển tư duy sáng tạo với những hình ảnh đáng yêu, đồng thời phát triển tư duy toán học và tư duy logic của trẻ. Điều đó được thể hiện rõ qua các trang bài tập\nMục tiêu kỹ năng: Trong bài học này các con sẽ tăng cường được khả năng quan sát của mình thông qua các trò chơi. Ngoài ra, các con còn biết chia sẻ và thể hiện những ý tưởng sáng tạo của mình với tập thể.",
  "3": "Trò chơi cơ bản: GIA ĐÌNH CỦA CHÚNG TA\nMục tiêu của trò chơi: Tìm ra các điểm tương đồng và khác biệt của các vật, tìm chúng với những đặc điểm khác nhau của vật khác\nMục tiêu kỹ năng: Trong bài học này phát triển thêm cho các con những kỹ năng như kỹ năng tham gia hoạt động nhóm.",
  "4": "Trò chơi nâng cao: GIA ĐÌNH CỦA CHÚNG TA\nMục tiêu của trò chơi: Tìm ra các điểm tương đồng và khác biệt của các vật, tìm chúng với những đặc điểm khác nhau của vật khác\nMục tiêu kỹ năng: Trong bài học này phát triển thêm cho các con những kỹ năng như kỹ năng tham gia hoạt động nhóm."
 },
 "306": {
  "1": "Mục tiêu kiến thức : Trong bài học tuần 1 các con sẽ được lắng nghe câu chuyện “ Rex đi cắm trại” và 6 trang của sách hoạt động (Trang 1-6). Thông qua câu chuyện các con nhận biết những điểm tương đồng giữa các đồ vật và hiểu về mối liên hệ thông qua lý luận tương tự bằng cách chơi một trò chơi tên là Cái gì đi với nhau, sử dụng bộ trò chơi, nhận biết màu sắc của các loại đồ khác nhau. Với 6 trang của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "2": "Mục tiêu kiến thức : Trong bài học này, con nhận biết mối tương quan giữa các sự vật, nhận biết điểm tương đồng, xác định tên gọi các loại phương tiện giao thông và môi trường di chuyển. Nhận diện mặt số và mối liên hệ thông qua những lập luận tương tự. Trò chơi hoạt động sẽ mang tới sự gần gũi, thân quen giúp các con dễ dàng tiếp thu nội dung kiến thức và tăng sự thích thú trong học tập. . Với 6 trang tiếp theo của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, làm quen với phép tính cộng trong phạm vi 10. Thông qua các hoạt động trò chơi giúp các con hiểu thêm các con số, các loại phương tiện giao thông, sự kết hợp làm việc nhóm và khả năng lắng nghe.",
  "3": "Mục tiêu kiến thức : Trong bài học này, con nhận biết mối tương quan giữa các sự vật, nhận biết điểm tương đồng, xác định tên gọi các hình ảnh, mối liên hệ thông qua những lập luận tương tự. Trò chơi hoạt động sẽ mang tới sự gần gũi, thân quen giúp các con dễ dàng tiếp thu nội dung kiến thức và tăng sự thích thú trong học tập, sự phối hợp làm việc nhóm, khả năng lắng nghe, suy luận. Với 6 trang tiếp theo của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, tách và gộp số trong phạm vi 10. Thông qua các hoạt động trò chơi giúp các con hiểu thêm về mối liên hệ của các đồ vật, suy luận logic, sự kết hợp làm việc nhóm và khả năng lắng nghe.",
  "4": "Mục tiêu kiến thức : Trong bài học này, con nhận biết mối tương quan giữa các con số, quy luật sắp xếp của các con số và khả năng phản xạ, thực hiện phép tính. Trò chơi hoạt động sẽ mang tới sự gần gũi, thân quen giúp các con dễ dàng tiếp thu nội dung kiến thức và tăng sự thích thú trong học tập, sự phối hợp làm việc nhóm, khả năng lắng nghe, suy luận. Với 6 trang tiếp theo của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau:\n \nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, tách và gộp số trong phạm vi 10. Thông qua các hoạt động trò chơi giúp các con có sự phản xạ nhanh trong việc tính toán, sự đồng cảm, cảm thông với cảm xúc của người khác"
 },
 "307": {
  "1": "Mục tiêu kiến thức : Trong bài học tuần 1 các con sẽ được lắng nghe câu chuyện “Ngày hội cánh đồng thú vị” và 6 trang của sách hoạt động (Trang 1-6). Thông qua câu chuyện các con nhận biết khái niệm hình kín và hình hở, phân biệt hình nào là hình kín, hình nào là hình hở. Đồng thời, các con học được cách chơi một số trò chơi đơn giản, chú ý nghe kỹ luật chơi trước khi chơi và không nên có ý đồ xấu với người khác. Với 6 trang của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "2": "Mục tiêu kiến thức : Trong bài học này, con vận dụng các bộ phận trên cơ thể mình để cùng các bạn trong nhóm tạo thành những hình ảnh đám mây trên những tấm thẻ. Các con tưởng tượng vận dụng hết sức sáng tạo của mình và học cách hợp tác với nhau để tạo hình. Trò chơi hoạt động sẽ mang tới sự gần gũi, thân quen giúp các con dễ dàng tiếp thu nội dung kiến thức và tăng sự thích thú trong học tập. Với 6 trang tiếp theo của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, làm quen với phép tính trừ trong phạm vi 10. Thông qua các hoạt động trò chơi giúp các con thể hiện khả năng sáng tạo và sự kết hợp làm việc nhóm, khả năng lắng nghe.",
  "3": "Mục tiêu kiến thức : Trong bài học tuần 3 các con sẽ được tham chơi trò chơi cơ bản “Shining star” và 6 trang của sách hoạt động (Trang 13 - 18). Thông qua trò chơi các con biết tạo thành các hình mở và hình kín và xác định số lượng bên trong hình tròn . Với 6 trang của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau\n Mục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng tập trung quan sát, chú ý vào hình dạng của một hình khối riêng biệt trong các hình khác nhau, nâng cao khả năng cho hoạt động hướng đến mục tiêu. Hình thành thói quen sắp xếp đồ vật bằng cách phân loại theo đặc điểm chung. Đồng thời rèn luyện cho học sinh khả năng suy nghĩ tìm ra chiến thuật để có thể giúp mình chiến  thắng được trò chơi. Khả năng quan sát, giải quyết tình huống trong quá trình chơi trò chơi.",
  "4": "Mục tiêu kiến thức : Trong bài học tuần 3 các con sẽ được tham chơi trò chơi nâng cao “Shining star” và 6 trang của sách hoạt động (Trang 19 - 24). Thông qua trò chơi rèn luyện và củng cố cho học sinh về khái niệm hình kín. Với 6 trang của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau: \n Mục tiêu kỹ năng: Trong bài học tuần này các con được rèn luyện kỹ năng quan sát, kỹ năng làm việc nhóm, phát triển ngôn ngữ và kỹ năng trình bày thông qua việc miêu tả và trình bày cách làm (sáng tạo) bươm bướm."
 },
 "308": {
  "1": "CÔNG VIÊN GIẢI TRÍ TOÀN CẦU CỦA REX\nMục tiêu của câu chuyện: Thông qua câu chuyện các con được học về các đặc điểm văn hóa và biểu tượng quốc gia như Vạn Lý Trường Thành của Trung Quốc, những chiếc cối xay gió ở Hà Lan, cây xương rồng ở Mexico, Kim Tự Tháp của Ai Cập, tàu con rùa cũng như cổng thành Sungnyemun của Hàn Quốc và xác định những biểu tượng quốc gia còn thiếu.\nMục tiêu kỹ năng: Trong bài học này phát triển thêm cho các con những kỹ năng trong cuộc sống như khi đi chơi phải nghe theo hướng dẫn của nhân viên công viên,",
  "2": "CÔNG VIÊN GIẢI TRÍ TOÀN CẦU CỦA REX\nMục tiêu của trò chơi vận động: Thông qua trò chơi các con hiểu được cách di chuyển theo từng bước của nhân vật tương ứng với số tung được trên xúc xắc. Đồng thời, con được giới thiệu Quốc kỳ của các Quốc gia khác nhau và quan sát tìm vị trí các các Quốc gia tương ứng trên bản đồ thế giới.\nMục tiêu kỹ năng: Trong bài học này phát triển thêm cho các con những kỹ năng hợp tác với các bạn, lắng nghe để hiểu cách chơi, phát triển cảm xúc xã hội cho các con.",
  "3": "Mục tiêu của trò chơi: Thông qua trò chơi các con được ôn tập, rèn luyện và có cơ hội phát triển kỹ năng xây dựng bằng cách chơi một trò chơi về tính từ.\nMục tiêu kỹ năng: Trong bài học này phát triển thêm cho các con những kỹ  năng tư duy về việc giải quyết một vấn đề thật linh hoạt và sáng tạo.",
  "4": "Mục tiêu của trò chơi: Thông qua trò chơi các con được ôn tập, rèn luyện và có cơ hội phát triển kỹ năng xây dựng bằng cách chơi một trò chơi về tính từ.\nMục tiêu kỹ năng: Trong bài học này phát triển thêm cho các con những kỹ  năng tư duy về việc giải quyết một vấn đề thật linh hoạt và sáng tạo"
 },
 "309": {
  "1": "Câu chuyện: \"GIÚP ĐỠ THẦY D\" \nMục tiêu kiến thức: Trong bài học tuần 1 các con sẽ được lắng nghe câu chuyện “ Giúp đỡ thầy D” và các kỹ năng tư duy. Thông qua câu chuyện học sinh biết cộng 1 vào 9 và hiểu rằng kết quả bằng 10.Hơn nữa, học sinh thông qua các hình ảnh trong truyện học được rằng khi có một bó 10 và 5 chiếc nữa thì tổng là 15. Thông qua bài tập, các con được rèn luyện các kỹ năng tư duy như sau\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, xác định quy luật sắp xếp.",
  "2": "Mục tiêu kiến thức: Trong bài học tuần 2 các con được tham gia trò chơi hoạt động “Đi chợ” và 6 trang của sách hoạt động tiếp theo (Trang 7-12). Thông qua trò chơi hoạt động học sinh hiểu về cách thức trao đổi hàng hóa giữa người mua và người bán. Biết cách trả 1 khoản tiền tương ứng với giá trị trên món hàng hóa. Hơn nữa, thông qua trò chơi học sinh biết cách quy đổi giá trị tiền, cách thối tiền nếu giá trị lớn. Với 6 trang của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, biết cách giao tiếp, ứng xử khi đi mua hàng hóa, học về cách quy đổi giá trị tiền. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "3": "Mục tiêu kiến thức: Trong bài học tuần 3 các con được tham gia trò chơi cơ bản “Đi chợ” và 6 trang của sách hoạt động tiếp theo (Trang 13-18). Thông qua trò chơi cơ bản học sinh hiểu về cách thức trao đổi hàng hóa giữa người mua và người bán. Đóng vai thành những người bán hàng để bán những món hàng có trong túi của mình và thu lại số tiền tương ứng với giá trị món hàng hóa. Với 6 trang của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, biết cách giao tiếp, ứng xử khi đi mua hàng hóa, học về cách quy đổi giá trị tiền. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "4": "Mục tiêu kiến thức: Trong bài học tuần 4 các con được tham gia trò chơi cơ bản “Đi chợ” và 6 trang của sách hoạt động tiếp theo (Trang 19-24). Thông qua trò chơi nâng cao học sinh hiểu về cách thức trao đổi hàng hóa giữa người mua và người bán. Đóng vai thành những người mua hàng để mua những món hàng có trong túi của mình và trả số tiền tương ứng với giá trị món hàng hóa. Đồng thời biết cách sử dụng đồng tiền hợp lý, quy đổi số tiền lớn thành các giá trị nhỏ hơn. Với 6 trang của sách hoạt động các con được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình. Đồng thời phát triển khả năng sáng tạo, ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình."
 },
 "310": {
  "1": "Câu chuyện: \"TIỆM KEM CỦA REX\" \nMục tiêu kiến thức: Trong bài học tuần 1 các con sẽ được lắng nghe câu chuyện “Tiệm kem của Rex” và các kỹ năng tư duy . Thông qua câu chuyện học sinh làm quen với khái niệm phân loại theo cấp bậc với 2 tiêu chuẩn ( vị kem và loại nhân phủ) thông qua quá trình tìm kiếm loại kem mà Anky, Tera, Dipo mong muốn. Học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phân tích, nhận biết các sự vật, hiện tượng xung quanh mình, các con biết cách phân loại bằng cách kết hợp các tiêu chí lại với nhau, không nên có ý đồ xấu với người khác nếu không sẽ gặp hậu quả đáng tiếc. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "2": "Mục tiêu kiến thức: Trong bài học tuần 2 các con được tham gia trò chơi hoạt động “Slow Slow” và các kỹ năng tư duy. Thông qua trò chơi hoạt động học sinh được làm quen với cách phân loại đơn giản, tìm thẻ hình phù hợp với các tiêu chuẩn phân loại. Học sinh được rèn luyện các kỹ năng tư duy như sau.\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và phản xạ nhanh chóng để tìm ra các thẻ hình tương ứng. Nhận biết sự vật sự việc thông qua việc tìm mối quan hệ giữa các hình ảnh, tổng hợp số và viết số tương ứng. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "3": "Mục tiêu kiến thức: Trong bài học tuần 3 các con được tham gia trò chơi hoạt động “Slow Slow” và các kỹ năng tư duy. Thông qua trò chơi cơ bản, học sinh được làm quen với kiến thức phân loại phức tạp theo tiêu chuẩn, quan sát linh hoạt, biết kết hợp các tiêu chí trên thẻ Slow để tìm ngay 2 thẻ tiêu chuẩn phù hợp. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và sự phản ứng linh hoạt, nhạy bén trong quá trình tìm các thẻ tiêu chuẩn. Rèn luyện khả năng suy luận phân tích để phát triển tư duy logic. Đồng thời phát triển khả năng làm việc nhóm, phối hợp nhịp nhàng công việc, ý tưởng giữa các thành viên trong nhóm. Cải thiện ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "4": "Mục tiêu kiến thức: Trong bài học tuần 4 các con được tham gia trò chơi “Slow Slow” và các kỹ năng tư duy. Thông qua trò chơi cơ bản, học sinh được làm quen với kiến thức phân loại phức tạp theo tiêu chuẩn, quan sát linh hoạt hai tiêu chí trên thẻ tiêu chuẩn để tìm thẻ Slow thỏa mãn. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và sự phản ứng linh hoạt, nhạy bén trong quá trình tìm các thẻ Slow. Rèn luyện khả năng sáng tạo bằng việc tưởng tượng, phát họa hình ảnh bằng mắt và thể hiện bằng nét vẽ. Đồng thời phát triển khả năng làm việc nhóm, phối hợp nhịp nhàng công việc, ý tưởng giữa các thành viên trong nhóm. Cải thiện ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình."
 },
 "310+": {
  "1": "Mục tiêu kiến thức: Trong bài học tuần ôn tập các con được tham gia trò chơi “ Ngôi sao lấp lánh” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi hoạt động học sinh biết cách phân biệt hình kín, hình hở. Ghép các mảnh ghép để tạo thành hình tròn khép kín và có số lượng ngôi sao theo yêu cầu. Dựa vào con số cho sẵn và xác định cần thêm bao nhiêu để được tổng 10. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, phán đoán và hiểu khái niệm hình kín, hình hở. Rèn luyện khả năng suy luận và định hướng trong không gian. Đồng thời phát triển khả năng ngôn ngữ diễn đạt, sự tự tin trình bày ý tưởng của mình.",
  "2": "Mục tiêu kiến thức: Trong bài học tuần ôn tập các con được tham gia trò chơi “ Vòng quanh thế giới” và các bài tập rèn luyện kỹ năng tư duy. Thông qua trò chơi hoạt động học sinh được học về cách đặt câu với thẻ hình tương ứng, di chuyển nhân vật khủng long theo số lượng âm tiết vừa đặt câu. Trò chơi rèn luyện cho học sinh khả năng diễn đạt, cung cấp thêm vốn từ vựng trong quá trình đặt câu và chiến thuật, suy luận để tìm số ấm tiết tương ứng để giúp mình di chuyển đến đất nước phù hợp và chiến thắng trò chơi. Thông qua các dạng bài tập, học sinh được rèn luyện các kỹ năng tư duy như sau:\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, suy luận và phát triển khả năng ngôn ngữ diễn đạt, tăng vốn từ vựng, tự tin trình bày ý tưởng của mình.",
  "3": "Mục tiêu kiến thức: Trong bài học tuần ôn tập các con các dạng bài tập hỗ trợ học sinh chuẩn bị tốt cho ký thi cuối kỳ sắp tới gồm các kỹ năng tư duy như sau\nMục tiêu kỹ năng: Bài học tuần này sẽ giúp cho các con tăng cường khả năng quan sát, suy luận, định hướng trong không gian và phát triển khả năng ngôn ngữ diễn đạt, tăng vốn từ vựng, tự tin trình bày ý tưởng của mình.",
  "4": "Mục tiêu kiến thức: Trong bài học tuần ôn tập các con các dạng bài tập hỗ trợ học sinh chuẩn bị tốt cho ký thi cuối kỳ sắp tới gồm các kỹ năng tư duy như sau.\nSau khi làm một số bài tập rèn tư duy các con sẽ làm bài kiểm tra cuối kì level 3 để kiểm tra đánh giá những nội dung được học trong thời gian qua và chuẩn bị chuyển lên level 4.\nSau khi con làm bài kiểm tra, cô giáo sẽ chấm bài và trao đổi kết quả cụ thể của con với bố mẹ."
 }
};
