"""Inject production features vao mau-giao.html va mau-giao-l4.html:
- CSS production_features.css -> truoc </style>
- JS production_features.js -> truoc </body>
- Toolbar HTML -> ngay sau <body>
- Confidentiality footer -> truoc </body>
- ARIA labels cho radar SVG
"""
import re, io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Read shared assets
with open(r'C:/Users/Admin/Downloads/wks/scraps/production_features.css', 'r', encoding='utf-8') as f:
    PROD_CSS = f.read()
with open(r'C:/Users/Admin/Downloads/wks/scraps/production_features.js', 'r', encoding='utf-8') as f:
    PROD_JS = f.read()

# Toolbar HTML - same for both
TOOLBAR_HTML = '''
<!-- ═════ PRODUCTION TOOLBAR (backup/dark/parent/template/analytics) ═════ -->
<div id="production-toolbar" data-tech="1">
  <button id="btn-dark-mode" onclick="__toggleDarkMode()" title="Bật/tắt chế độ tối">🌙</button>
  <button id="btn-parent-mode" onclick="__toggleParentMode()" title="Chế độ phụ huynh: ẩn phần kỹ thuật">👪 Chế độ phụ huynh</button>
  <span class="sep"></span>
  <button onclick="__exportBackupMG()" title="Sao lưu toàn bộ data ra file JSON">💾 Backup</button>
  <button onclick="document.getElementById('restore-file-input').click()" title="Khôi phục từ file JSON">📂 Restore</button>
  <input type="file" id="restore-file-input" accept=".json" onchange="if(this.files[0]) __importBackupMG(this.files[0])">
  <span class="sep"></span>
  <button onclick="__downloadXlsxTemplate(typeof __ATOMIC_CRITERIA_L3 !== 'undefined' && __ATOMIC_CRITERIA_L3.length === 65 ? 'L4' : 'L3')" title="Tải xlsx template trống">📥 Template</button>
  <button onclick="__showClassAnalyticsMG()" title="Xem analytics toàn lớp từ batch import">📊 Analytics lớp</button>
</div>
'''

# Confidentiality footer
CONFIDENTIALITY_HTML = '''
<!-- ═════ CONFIDENTIALITY FOOTER ═════ -->
<div class="confidentiality-footer">
  <b>⚠ CONFIDENTIAL — Đánh giá nội bộ WonderKids Edu</b><br>
  Báo cáo này chứa thông tin cá nhân của trẻ em — vui lòng không chia sẻ ngoài phạm vi GV-Phụ huynh.
  Mọi nội dung đánh giá tuân thủ quy định bảo mật dữ liệu trẻ em theo NĐ 13/2023/ND-CP.
  <br><span style="font-size:9.5px;opacity:.75">© 2025 WonderKids Edu. Generated by WonderKids Report v2.0.</span>
</div>
'''

# ARIA labels addition
def add_aria_to_svgs(html):
    # Hero radar
    html = re.sub(
        r'<svg id="radar-chart"([^>]*)>',
        r'<svg id="radar-chart"\1 role="img" aria-label="Biểu đồ radar 4 nhóm năng lực tư duy chính của bé">',
        html, count=1
    )
    # Mini radar SVGs
    html = re.sub(
        r'<svg class="mini-radar-svg"([^>]*)>',
        lambda m: f'<svg class="mini-radar-svg"{m.group(1)} role="img" aria-label="Biểu đồ radar chi tiết theo từng kỹ năng">',
        html
    )
    # Autonomy chart
    html = re.sub(
        r'<svg id="mg-autonomy-chart"([^>]*)>',
        r'<svg id="mg-autonomy-chart"\1 role="img" aria-label="Biểu đồ mức độ tự chủ của bé khi làm bài, gauge chỉ số tổng + 5 thanh ladder theo mức hỗ trợ">',
        html, count=1
    )
    # Bloom pyramid
    html = re.sub(
        r'<svg id="mg-bloom-pyramid"([^>]*)>',
        r'<svg id="mg-bloom-pyramid"\1 role="img" aria-label="Tháp Bloom Taxonomy 5 cấp năng lực nhận thức kèm tỉ lệ % bé đạt mỗi cấp">',
        html, count=1
    )
    return html

def inject_file(path, level_label):
    with open(path, 'r', encoding='utf-8') as f:
        html = f.read()

    # 1. Inject CSS truoc </style> dau tien (main style block)
    css_marker = '/* ───── AUTONOMY chart'
    # find last </style> before this anchor — but anchor in style block, so just insert before next </style>
    # Better: find pattern "}</style>" and inject CSS right before it
    if 'PROD_CSS_INJECTED' not in html:
        css_inject = '\n/* ═════ PRODUCTION FEATURES CSS ═════ */\n/* PROD_CSS_INJECTED */\n' + PROD_CSS + '\n'
        # Inject before first </style>
        m = re.search(r'</style>', html)
        if m:
            html = html[:m.start()] + css_inject + html[m.start():]
            print(f'  ✓ CSS injected ({len(css_inject)} chars)')
        else:
            print('  ✗ </style> not found, CSS skip')
    else:
        print('  ℹ CSS already injected, skipping')

    # 2. Inject toolbar HTML right after <body>
    if 'id="production-toolbar"' not in html:
        html = html.replace('<body>', '<body>\n' + TOOLBAR_HTML, 1)
        print('  ✓ Toolbar HTML injected')

    # 3. Inject confidentiality footer + JS right before </body>
    # check for unique JS function name to avoid false positive with CSS class
    if '__exportBackupMG' not in html:
        injection = CONFIDENTIALITY_HTML + '\n<script>\n/* ═════ PRODUCTION FEATURES JS ═════ */\n' + PROD_JS + '\n</script>\n'
        html = html.replace('</body>', injection + '</body>', 1)
        print('  ✓ Footer + JS injected')
    else:
        print('  ℹ Footer + JS already injected, skipping')

    # 4. Add ARIA labels to SVGs
    html_new = add_aria_to_svgs(html)
    if html_new != html:
        html = html_new
        print('  ✓ ARIA labels added to SVGs')

    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f'  → Saved {len(html)} chars')

for path, label in [
    (r'C:/Users/Admin/Downloads/wks/mau-giao.html', 'L3'),
    (r'C:/Users/Admin/Downloads/wks/mau-giao-l4.html', 'L4'),
]:
    print(f'\n=== Processing {path} ({label}) ===')
    inject_file(path, label)

print('\nAll done.')
