"""Inject just the JS function definitions (chua duoc inject do idempotency bug)."""
import io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

with open(r'C:/Users/Admin/Downloads/wks/scraps/production_features.js', 'r', encoding='utf-8') as f:
    PROD_JS = f.read()

CONFIDENTIALITY_HTML = '''
<!-- ═════ CONFIDENTIALITY FOOTER ═════ -->
<div class="confidentiality-footer">
  <b>⚠ CONFIDENTIAL — Đánh giá nội bộ WonderKids Edu</b><br>
  Báo cáo này chứa thông tin cá nhân của trẻ em — vui lòng không chia sẻ ngoài phạm vi GV-Phụ huynh.
  Mọi nội dung đánh giá tuân thủ quy định bảo mật dữ liệu trẻ em theo NĐ 13/2023/ND-CP.
  <br><span style="font-size:9.5px;opacity:.75">© 2025 WonderKids Edu. Generated by WonderKids Report v2.0.</span>
</div>
'''

INJECTION_MARKER = '<!-- PROD_JS_INJECTED -->'

for path in [
    r'C:/Users/Admin/Downloads/wks/mau-giao.html',
    r'C:/Users/Admin/Downloads/wks/mau-giao-l4.html',
]:
    print('Processing', path)
    with open(path, 'r', encoding='utf-8') as f:
        html = f.read()
    if INJECTION_MARKER in html:
        print('  Already has marker — skip')
        continue
    # Check if window.__exportBackupMG is REALLY defined (not just referenced)
    has_def = 'window.__exportBackupMG = function' in html
    if has_def:
        print('  Function def found — just add marker')
        html = html.replace('</body>', INJECTION_MARKER + '\n</body>', 1)
    else:
        print('  Function NOT defined — inject JS + footer + marker')
        injection = (INJECTION_MARKER + '\n' +
                     CONFIDENTIALITY_HTML + '\n' +
                     '<script>\n/* ═════ PRODUCTION FEATURES JS ═════ */\n' +
                     PROD_JS + '\n</script>\n')
        html = html.replace('</body>', injection + '</body>', 1)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    print('  Saved', len(html), 'chars')
print('Done')
